parallel-jobs = 1

[Google_Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
app-name = "GPhotos"
arch = "arm64-v8a"
version = "auto"
included-patches = "'Enable DCIM folders backup control'"